#include <iostream>
#include <string>
#include "problem1_10.hpp"

using namespace std;

// ------------------------------------------------------------------------------------------------ //
// Problem 1: Multiples of 3 and 5                                                                  //
//                                                                                                  //
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.  //
// The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.        //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum1()
{
    cout << "Problem 1\t\t:\tMultiples of 3 and 5" << endl;

    int toplam = 0;

    for (int n = 0; n < 1000; ++n)
    {
        if (n % 3 == 0 || n % 5 == 0)
        {
            toplam += n;
        }
    }

    cout << "Solution 1\t:\t" << toplam << endl;
    cout << "\t\t\t---------------------------" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 2: Even Fibonacci numbers                                                                //
//                                                                                                  //
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.           //
// By starting with 1 and 2, the first 10 terms will be:                                            //
//                            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                //
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,      //
// find the sum of the even-valued terms.                                                           //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum2()
{
    cout << "Problem 2\t\t:\tEven Fibonacci numbers" << endl;

    unsigned long toplam = 0;
    unsigned long n1 = 1, n2 = 2;

    while(n1 < 4000000)
    {
        if (n1 % 2 == 0)
        {
            toplam += n1;
        }

        n2 = n1 + n2;
        n1 = n2 - n1;
    }

    cout << "Solution 2\t:\t" << toplam << endl;
    cout << "\t\t\t---------------------------" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 3: Largest prime factor                                                                  //
//                                                                                                  //
// The prime factors of 13195 are 5, 7, 13 and 29.                                                  //
// What is the largest prime factor of the number 600851475143 ?                                    //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum3()
{
    cout << "Problem 3\t\t:\tLargest prime factor" << endl;

    long long i = 0;
    long long n = 600851475143;

    for (i = 2; n > 1; i++)
    {
        while (n % i == 0)
        {
            n /= i;
        }
    }

    cout << "Solution 3\t:\t" << i - 1 << endl;
    cout << "\t\t\t---------------------------" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 4: Largest palindrome product                                                            //
//                                                                                                  //
// A palindromic number reads the same both ways.                                                   //
// The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.           //
// Find the largest palindrome made from the product of two 3-digit numbers.                        //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum4()
{
    cout << "Problem 4\t\t:\tLargest palindrome product" << endl;

    int min = 99, max = 999, sonuc = 0, carpan1 = 0, carpan2 = 0;

    for (int i = max; i > min; i--)
    {
        for (int j = i; j > min; j--)
        {
            int k = i * j;

            if (k <= sonuc)
            {
                break;
            }

            std::string sayiString = std::to_string(k);
            bool durum = true;

            for (int l = 0, r = sayiString.size() - 1; l < r; l++, r--)
            {
                if (sayiString[l] != sayiString[r])
                {
                    durum = false;
                    break;
                }
            }

            if (durum)
            {
                sonuc = k;
                carpan1 = i;
                carpan2 = j;
            }
        }
    }

    cout << "Solution 4\t:\t" << carpan1 << " * " << carpan2 << " = " << sonuc << endl;
    cout << "\t\t\t---------------------------" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 5: Smallest multiple                                                                     //
//                                                                                                  //
// 2520 is the smallest number that can be                                                          //
// divided by each of the numbers from 1 to 10 without any remainder.                               //
// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?//
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum5()
{
    cout << "Problem 5\t\t:\tSmallest multiple" << endl;

    int sayi = 2520;
    bool durum = false;

    while (sayi)
    {
        if (sayi % 11 == 0 &&
            sayi % 13 == 0 &&
            sayi % 14 == 0 &&
            sayi % 16 == 0 &&
            sayi % 17 == 0 &&
            sayi % 18 == 0 &&
            sayi % 19 == 0 &&
            sayi % 20 == 0)
        {
            durum = true;
        }

        if (durum == true)
        {
            break;
        }
        else
        {
            sayi += 2520;
        }

    }

    cout << "Solution 5\t:\t" << sayi << endl;
    cout << "\t\t\t---------------------------" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 6: Sum square difference                                                                 //
//                                                                                                  //
// The sum of the squares of the first ten natural numbers is,                                      //
//                                  12 + 22 + ... + 102 = 385                                       //
// The square of the sum of the first ten natural numbers is,                                       //
//                              (1 + 2 + ... + 10)2 = 552 = 3025                                    //
// Hence the difference between the sum of the squares of the first ten natural numbers and         //
// the square of the sum is 3025 − 385 = 2640. Find the difference between                          //
// the sum of the squares of the first one hundred natural numbers and the square of the sum.       //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum6()
{
    cout << "Problem 6\t\t:\tSum square difference" << endl;
    cout << "\t\t\t---------------------------" << endl;
}

void Problem1_10::Cozum7()
{
    cout << "Problem 7\t\t:\t10001st prime" << endl;
    cout << "\t\t\t---------------------------" << endl;
}

void Problem1_10::Cozum8()
{
    cout << "Problem 8\t\t:\tLargest product in a series" << endl;
    cout << "\t\t\t---------------------------" << endl;
}

void Problem1_10::Cozum9()
{
    cout << "Problem 9\t\t:\tSpecial Pythagorean triplet" << endl;
    cout << "\t\t\t---------------------------" << endl;
}

void Problem1_10::Cozum10()
{
    cout << "Problem 10\t:\tSummation of primes" << endl;
    cout << "\t\t\t---------------------------" << endl;
}
