#include <iostream>
#include "problem1_10.hpp"

using namespace std;

// ------------------------------------------------------------------------------------------------ //
// Problem 1: Multiples of 3 and 5                                                                  //
//                                                                                                  //
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.  //
// The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.        //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum1()
{
    cout << "Problem 1\t\t:\tMultiples of 3 and 5" << endl;

    int toplam = 0;

    for (int n = 0; n < 1000; ++n)
    {
        if (n % 3 == 0 || n % 5 == 0)
        {
            toplam += n;
        }
    }

    cout << "Solution 1\t:\t" << toplam << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

// ------------------------------------------------------------------------------------------------ //
// Problem 2: Even Fibonacci numbers                                                                //
//                                                                                                  //
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.           //
// By starting with 1 and 2, the first 10 terms will be:                                            //
//                            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                //
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,      //
// find the sum of the even-valued terms.                                                           //
// ------------------------------------------------------------------------------------------------ //
void Problem1_10::Cozum2()
{
    cout << "Problem 2\t\t:\tEven Fibonacci numbers" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum3()
{
    cout << "Problem 3\t\t:\tLargest prime factor" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum4()
{
    cout << "Problem 4\t\t:\tLargest palindrome product" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum5()
{
    cout << "Problem 5\t\t:\tSmallest multiple" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum6()
{
    cout << "Problem 6\t\t:\tSum square difference" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum7()
{
    cout << "Problem 7\t\t:\t10001st prime" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum8()
{
    cout << "Problem 8\t\t:\tLargest product in a series" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum9()
{
    cout << "Problem 9\t\t:\tSpecial Pythagorean triplet" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}

void Problem1_10::Cozum10()
{
    cout << "Problem 10\t\t:\tSummation of primes" << endl;
    cout << "\t\t\t---\t\t---" << endl;
}
